server:
  error:
    whitelabel:
      enabled: true
  servlet:
    encoding:
      force: true
spring:
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  resources:
    add-mappings: false
mooc:
  jwt:
    access-toke-expire-time: 300000 
    refresh-toke-expire-time: 2592000000